FROM node:20-alpine

WORKDIR /app

COPY  package*.json tsconfig.json ./

RUN npm install

COPY config.ts .

COPY src ./src

COPY prisma ./prisma

RUN npx prisma generate

EXPOSE 8000

CMD ["npm", "run", "dev:hot"]